### PR TITLE
Fix "reflection.tscn' appears to be invalid/corrupt." warning when opening project

### LINKED ISSUE #5: "Scene file 'reflection.tscn' appears to be invalid/corrupt." on open
Can't open the project in v4.0.dev.custom_build [9dd1debaf]

Errors in console when trying to open:
```
SCRIPT ERROR: Parse Error: Identifier "BUTTON_LEFT" not declared in the current scope.
          at: GDScript::reload (res://camera.gd:37)
SCRIPT ERROR: Parse Error: Identifier "translation" not declared in the current scope.
          at: GDScript::reload (res://camera.gd:75)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules\gdscript\gdscript.cpp:840)
ERROR: No loader found for resource: res://reflection/reflection.GIProbe_data.res.
   at: (core\io\resource_loader.cpp:217)
ERROR: res://reflection/reflection.tscn:110 - Parse Error: [ext_resource] referenced non-loaded resource at: res://reflection/reflection.GIProbe_data.res
   at: _parse_ext_resource (scene\resources\resource_format_text.cpp:170)
ERROR: res://reflection/reflection.tscn:110 - Parse Error: [ext_resource] referenced non-loaded resource at: res://reflection/reflection.GIProbe_data.res
   at: _parse_node_tag (scene\resources\resource_format_text.cpp:269)
ERROR: Failed loading resource: res://reflection/reflection.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:210)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor\editor_data.cpp:539)
```

### PR DESCRIPTION
**Pull request by T-rvw**
This PR fixed corrupt when opening godot-reflection project by latest godot master branch.

We can open editor without "reflection.tscn' appears to be invalid/corrupt." pop up. Closes #5 .

But there are errors about VoxelGI(The old name is GIProbe) in the console window. As @Calinou mentioned, it needs godot engine's fixes. You can set invisible for VoxelGI node to avoid these errors and warnings.

H8OQ`0RY56Z3USY~(5A9~XA

Here is a list about what changed.
```
Mannual fixes:
    GDScript:
        BUTTON_LEFT -> MOUSE_BUTTON_LEFT
        translation -> position

    TSCN:
        Transform   -> Transform3D
        GIProbe     -> VoxelGI
        GIProbeData -> VoxelGIData

Automation fixes:
    TSCN:
        uid generation
        ext resource order
        id number -> string
        MeshInstance3D.material -> MeshInstance3D.surface_material_override
        
    .png.import:
        uid generation
        process/invert_color -> process/normal_map_invert_y

    .glb.import:
        removed many params
            ...
        added new params
            animation/bake_reset_animation=true
            import_script/path=""
            _subresources={
            }

    project.godot:
    events.alt      -> events.alt_pressed
    events.shift    -> events.shift_pressed
    events.meta     -> events.meta_pressed
    events.command  -> events.command_pressed
```

### CODE REVIEW

**Comment by Calinou** [comment]
According to the screenshot, materials are missing. Do you know if you could restore them?

> But there are errors in the console window. I need to have a look what they mean and how to fix.

These errors are caused by the engine itself and have already been reported on the main Godot repository. There's no way to fix them from the project.

**Comment by T-rvw** [comment]
@Calinou 
`Note: If some materials don't show up, try selecting reflection/reflection.obj in the FileSystem dock, go to the Import dock then click Reimport.`

I tried to reimport `./reflection/models/reflection.glb` but materials still don't show up. (reflection.obj has been removed now.) I need to have a research on how material works. `./reflection/models/reflection.glb.import` is suspicious. It removed many old params.

`There's no way to fix them from the project.`
Thanks for your information. So what I can do next is only to restore materials.

**Comment by T-rvw** [comment]
@Calinou Material issues have been fixed. The .blend project missed some texture files. So I used `File->External Data->Find Missing Files` command to fix this project.

I just exported it to .glb format by default. But the file size is 4x larger than the old one. Do I need to modify some export setttings? (blender-2.93.4)

**Comment by Calinou** [comment]
Superseded by https://github.com/Calinou/godot-reflection/pull/7. Thanks for the contribution nonetheless!

**Pull request closed without merging**
